---
name: Code Quality
on:
  push:
    branches:
      - master
    pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install requirements
        run: |
          python -m pip install -r requirements.txt
      - name: Lint
        run: make lint
  sanity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install requirements
        run: |
          python -m pip install -r requirements.txt
      - name: Sanity
        run: make sanity
